// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmi7yBY3WTjLyciXXvkkYfQS9HG4X_emk',
    appId: '1:377686290683:web:1142185db0096e2630005e',
    messagingSenderId: '377686290683',
    projectId: 'saad-ardati',
    authDomain: 'saad-ardati.firebaseapp.com',
    storageBucket: 'saad-ardati.appspot.com',
    measurementId: 'G-25BFM7DC0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdjFltChJEaXam9QarQRaxCmB0uZP-DH0',
    appId: '1:377686290683:android:fbb73ec88ca743c430005e',
    messagingSenderId: '377686290683',
    projectId: 'saad-ardati',
    storageBucket: 'saad-ardati.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAtInTUPk9FQ1H1zcK5qIZAMOio3SuG-Q',
    appId: '1:377686290683:ios:8e98493dd2dab99930005e',
    messagingSenderId: '377686290683',
    projectId: 'saad-ardati',
    storageBucket: 'saad-ardati.appspot.com',
    iosClientId: '377686290683-r07f7hu7f6nnb5mqiond6ko54lcbr326.apps.googleusercontent.com',
    iosBundleId: 'dev.saadardati.pocketjenna.pocketjenna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAtInTUPk9FQ1H1zcK5qIZAMOio3SuG-Q',
    appId: '1:377686290683:ios:db3f2376d06e092a30005e',
    messagingSenderId: '377686290683',
    projectId: 'saad-ardati',
    storageBucket: 'saad-ardati.appspot.com',
    iosClientId: '377686290683-q956stmu2899em7q6mv614v26jlfsfrl.apps.googleusercontent.com',
    iosBundleId: 'dev.saadardati.pocketjenna',
  );
}
