// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABjpkJUp-BDXe4GIhOfYYWl-0twmOhsqs',
    appId: '1:653039980755:web:6d7dd366f0400351068426',
    messagingSenderId: '653039980755',
    projectId: 'pocket-jenna',
    authDomain: 'pocket-jenna.firebaseapp.com',
    storageBucket: 'pocket-jenna.appspot.com',
    measurementId: 'G-XKJ8E7TM9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWhHL-75zsY4GJb7-wCoRDHgFnCwkjh1A',
    appId: '1:653039980755:android:c8bbd7666c0b97cd068426',
    messagingSenderId: '653039980755',
    projectId: 'pocket-jenna',
    storageBucket: 'pocket-jenna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXFyIfs9OtKGGPdfY0fbdWAVFKyEJubPw',
    appId: '1:653039980755:ios:de0963ffea5e9df1068426',
    messagingSenderId: '653039980755',
    projectId: 'pocket-jenna',
    storageBucket: 'pocket-jenna.appspot.com',
    iosClientId: '653039980755-pt0hk5prebd357bhgje26t1kjt08std4.apps.googleusercontent.com',
    iosBundleId: 'dev.saadardati.pocketjenna.pocketjenna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXFyIfs9OtKGGPdfY0fbdWAVFKyEJubPw',
    appId: '1:653039980755:ios:5af4136d5a45ca6b068426',
    messagingSenderId: '653039980755',
    projectId: 'pocket-jenna',
    storageBucket: 'pocket-jenna.appspot.com',
    iosClientId: '653039980755-55t2elon4ju1luecm1i2k24dmch4tcno.apps.googleusercontent.com',
    iosBundleId: 'dev.saadardati.pocketjenna',
  );
}
