app_id: dev.saadardati.pocketjenna
publisher: Saad Ardati
publisher_url: https://github.com/BirjuVachhani/PocketJenna
display_name: Pocket Jenna
install_dir_name: PocketJenna
setup_icon_file: app_icon.ico
create_desktop_icon: true
script_template: inno_setup.iss
locales:
  - en